### PR TITLE
fix: revert build change

### PR DESCRIPTION
**Pull request by chenrui333**
revert #62 as it broke the homebrew build

cc @Felixoid @rwos

### CODE REVIEW

**Comment by rwos** [comment]
is there like a build error somewhere? Like, what is broken exactly?

**Comment by chenrui333** [comment]
this is the error log, https://github.com/Homebrew/homebrew-core/actions/runs/7006155254/job/19057588235

**Comment by rwos** [comment]
@chenrui333 I just tagged `v1.9.1` which should work again, thanks for the report!

**Comment by chenrui333** [comment]
np

**Pull request closed without merging**
