### PR TITLE
MSVC build support + smooth animation for Windows

### PR DESCRIPTION
**Pull request by Joker-vD**
* Proper defines to compile for Microsoft Visual Studio, including awareness of Unicode paths
* Complete rewrite of line_at() to make animation on Windows smooth - fputc() is incredibly slow in unbuffered mode

Well, that's pretty much it. Also, since MSVC doesn't support C99, I moved some variable declarations around, but that's too minor to mention.

### CODE REVIEW

**Comment by Joker-vD** [comment]
Oh, and it's still building on Linux without warnings or anything, tested on Ubuntu 12.04 LTS, gcc 4.6.3, libc 2.15.

**Comment by rwos** [comment]
Thanks for the PR! Kinda regretting I ever accepted windows support, but what you gonna do, right? ;)

I don't really understand the unicode part . There's no need to use wide chars/strings here, we don't access single chars - whatever comes out of `getenv` is plugged into `execv` and that should work with literally anything that doesn't contain `NUL`. And it does, on Linux:

```
$ ln -s /usr/bin/git /tmp/öh
$ GIT=/tmp/öh gti --version
...
git version 2.1.4
```

If `fputc` is unbuffered on windows, then I'd rather replace that with a creative `printf` invocation than with that kind of buffer-juggling. Also, `malloc` isn't checked for success.

**Comment by Joker-vD** [comment]
Unicode part on Windows is frustrating. Process's environment is stored in UTF-16. `getenv()` returns a string converted from UTF-16 into legacy code page. If this code page doesn't contain some symbols from that string, they're replaced with "?". Then, `exec`/`spawn` convert its arguments from that legacy code page into UTF-16. Naturally, "?" stays "?", and such paths don't exist. 

`fputc` is just slow in unbuffered mode, and removing `setvbuf()` call makes ugly screen. Now that I think of it, maybe putting `fflush()` right in the end of original `line_at()` would fix that.

And as for `malloc()`—hm. Well, normally it wouldn't be asked for more than 640 bytes, so I doubt it would ever fail, but OK, I'll put the test in.

**Comment by Joker-vD** [comment]
Apparently, the variant without `setvbuf()` but with `fflush()` inserted at the end of Windows version of `line_at()` gives the same speed as with "that kind of buffer-juggling". Removes need to use `malloc()`, too.

All right, then I'll do a new commit with that fix for `line_at()`, and remove Unicode awareness.

**Pull request closed without merging**
